# -*- coding: utf-8 -*-
"""store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyXIm3n4_0B8HrNxZY58l_jVTvvU3kCY

# Explanation:
* Stores text chunks as vectors using FAISS + SentenceTransformers.

* Enables fast, relevant semantic search.
"""

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

class LocalVectorStore:
    def __init__(self):
        self.model = SentenceTransformer("all-MiniLM-L6-v2")
        self.texts = []
        self.index = faiss.IndexFlatL2(384)

    def add_texts(self, docs):
        chunks = [doc.page_content for doc in docs]
        embeddings = self.model.encode(chunks)
        self.texts.extend(chunks)
        self.index.add(np.array(embeddings, dtype='float32'))

    def search(self, query, k=3):
        query_vec = self.model.encode([query])
        distances, indices = self.index.search(np.array(query_vec, dtype='float32'), k)
        return [self.texts[i] for i in indices[0]]