# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6l0tX4o3JYSNL3LJzrzUvIo9AjA5tec

# Explanation
* This is the main UI using Streamlit.

* Users upload files and ask questions.

* It talks to the Coordinator to process files and handle queries.
"""

import streamlit as st
from coordinator import Coordinator

st.set_page_config(page_title="Agentic RAG Chatbot", layout="wide")
st.title("🤖 Agentic RAG Chatbot (Local, No API Key)")

coord = Coordinator()

st.sidebar.header("📄 Upload Documents")
uploaded_files = st.sidebar.file_uploader("Upload files", type=["pdf", "txt", "docx", "csv", "pptx"], accept_multiple_files=True)

if uploaded_files:
    with st.spinner("Processing documents..."):
        for file in uploaded_files:
            with open(file.name, "wb") as f:
                f.write(file.read())
        coord.handle_upload(uploaded_files)
    st.sidebar.success("Documents processed!")

query = st.text_input("Ask a question about the documents:")
if query:
    with st.spinner("Generating answer..."):
        result = coord.handle_query(query)
        st.markdown("### 💬 Answer")
        st.write(result['payload']['answer'])

        st.markdown("### 📚 Source Context")
        for chunk in result['payload']['sources']:
            st.info(chunk)