# -*- coding: utf-8 -*-
"""coordinator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQw0-dhJBovzb_6cuxy1LJX3QnsdL3Zt

# Explanation :


*   This is the controller that connects all 3 agents together.



*   Handles file ingestion and question answering in sequence.
"""

from agents.ingestion_agent import IngestionAgent
from agents.retrieval_agent import RetrievalAgent
from agents.llm_response_agent import LLMResponseAgent

class Coordinator:
    def __init__(self):
        self.ingestor = IngestionAgent()
        self.retriever = RetrievalAgent()
        self.llm_agent = LLMResponseAgent()

    def handle_upload(self, files):
        mcp_msg = self.ingestor.process(files)
        docs = mcp_msg['payload']['docs']
        self.retriever.build_store(docs)

    def handle_query(self, query):
        retrieval_msg = self.retriever.retrieve(query)
        ctx = retrieval_msg['payload']['retrieved_context']
        final_msg = self.llm_agent.generate_answer(ctx, query)
        return final_msg