# -*- coding: utf-8 -*-
"""mcp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hftPnIuilkjcX7jZstQrc3tlih33-n5g

# Explanation:
Helper to generate **structured messages** for communication between agents.
"""

import uuid

def create_mcp_message(sender, receiver, msg_type, payload):
    return {
        "sender": sender,
        "receiver": receiver,
        "type": msg_type,
        "trace_id": str(uuid.uuid4()),
        "payload": payload
    }