# -*- coding: utf-8 -*-
"""parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DUo13q8kQjFxPcZkPoxZweXbsoo8SUd

# Explanation:
Uses **LangChain loaders** to extract text from various file formats.
"""

from langchain.document_loaders import PyMuPDFLoader, TextLoader, CSVLoader, Docx2txtLoader, UnstructuredPowerPointLoader

def load_document(file_path, file_type):
    if file_type == "pdf":
        loader = PyMuPDFLoader(file_path)
    elif file_type == "txt":
        loader = TextLoader(file_path)
    elif file_type == "csv":
        loader = CSVLoader(file_path)
    elif file_type == "docx":
        loader = Docx2txtLoader(file_path)
    elif file_type == "pptx":
        loader = UnstructuredPowerPointLoader(file_path)
    else:
        raise ValueError("Unsupported file type")

    return loader.load()