# -*- coding: utf-8 -*-
"""parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DUo13q8kQjFxPcZkPoxZweXbsoo8SUd

# Explanation:
Uses **LangChain loaders** to extract text from various file formats.
"""

import fitz  # PyMuPDF
import pandas as pd
from docx import Document
from pptx import Presentation

class SimpleDoc:
    def __init__(self, page_content):
        self.page_content = page_content

def load_document(file_path, file_type):
    docs = []

    if file_type == "pdf":
        doc = fitz.open(file_path)
        for page in doc:
            docs.append(SimpleDoc(page.get_text()))
    elif file_type == "txt":
        with open(file_path, 'r', encoding='utf-8') as f:
            docs.append(SimpleDoc(f.read()))
    elif file_type == "csv":
        df = pd.read_csv(file_path)
        docs.append(SimpleDoc(df.to_string()))
    elif file_type == "docx":
        doc = Document(file_path)
        text = "\n".join([para.text for para in doc.paragraphs])
        docs.append(SimpleDoc(text))
    elif file_type == "pptx":
        prs = Presentation(file_path)
        text = ""
        for slide in prs.slides:
            for shape in slide.shapes:
                if hasattr(shape, "text"):
                    text += shape.text + "\n"
        docs.append(SimpleDoc(text))
    else:
        raise ValueError("Unsupported file type")

    return docs