# -*- coding: utf-8 -*-
"""ingestion_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKx3yFjFLrz9pX1j0kCTahQojp2wNYXU

# Explanation :


*   Reads and parses each uploaded file.

* Converts them into plain text chunks and sends via MCP message.
"""

from utils.mcp import create_mcp_message
from utils.parser import load_document

class IngestionAgent:
    def process(self, files):
        all_docs = []
        for file in files:
            ext = file.name.split('.')[-1].lower()
            docs = load_document(file.name, ext)
            all_docs.extend(docs)

        return create_mcp_message(
            sender="IngestionAgent",
            receiver="RetrievalAgent",
            msg_type="DOCUMENTS_PARSED",
            payload={"docs": all_docs}
        )