# -*- coding: utf-8 -*-
"""retrieval_agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17TCtZ9ER02BzvZ53Eg8PmBdsqx2uK9nl

# Explanation:


*   Creates a vector store from parsed text.
*   Handles semantic search using sentence-transformers + FAISS.
"""

from vector_store.store import LocalVectorStore
from utils.mcp import create_mcp_message

class RetrievalAgent:
    def __init__(self):
        self.db = LocalVectorStore()

    def build_store(self, docs):
        self.db.add_texts(docs)

    def retrieve(self, query, k=3):
        chunks = self.db.search(query, k)
        return create_mcp_message(
            sender="RetrievalAgent",
            receiver="LLMResponseAgent",
            msg_type="RETRIEVAL_RESULT",
            payload={"retrieved_context": chunks, "query": query}
        )